---
local_servers:
  hosts:
   local_server: 
    ansible_host: 192.168.100.158
    remote_user: tdubiel
    become: yes

remote_servers:
  hosts:
   remote_server: 
    ansible_host: 3.20.2.39
    remote_user: ec2-user
    become: yes
ios:
  hosts:
    sandbox-iosxe-latest-1.cisco.com:
    sandbox-iosxe-recomm-1.cisco.com:
  