---
- name: Second Router
  hosts: sandbox-iosxe-recomm-1.cisco.com
  gather_facts: false
  vars:
    ansible_user: developer
    ansible_password: 'lastorangerestoreball8876'
  tasks:
    - name: Create User Admin
      cisco.ios.ios_user:
        name: admin
        configured_password: 'C1sco12345'
        privilege: 15
        state: present